### ISSUE TITLE
[Doubt] About this repos

### ISSUE THREAD

**Issue by XorTroll** [valentinvanelslande/3dJS#1]
I'm XorTroll, the original author of 3dJS.
I deleted my repos because I'm developing a bigger project than this one focused on Switch.
I must tell you that this project has a very poor JS core, and that many things there are deprecated or could be coded way more efficiently. I just did this project as a test to bind JS to a 3DS system.

Are you planning to develop a bigger project from this, or it's just a simple fork? Just curiosity...
Obviously do whatever you want with it.

My new project: [Brew.js - Switch](https://github.com/BrewJS/Switch)

**Comment by valentinvanelslande** [comment]
is a simple fork
